### ISSUE TITLE
predict(...., type= "response", se_fit = T) gives both est and se as link 

### ISSUE THREAD

**Issue by matteba** [pbs-assess/sdmTMB#140]
Hello, 
When I try to use the preditiction function with (....,,type = "response", se_fit=T) to calculate the standard error as well, the output object automatically returns the "est" and "se" as link instead of response. 
I know that I can trasform both est and se by exp(est)/(1+exp(est)) to obtain the response prediction, but I was wondering if you were aware of this. 
Thanks 
Matteo

**Comment by seananderson** [comment]
Hi Matteo, thanks for pointing out this inconsistency. There are a frustrating number of permutations between link/response, regular/simulation/mcmc output, with/without SEs, with/without random fields. I'll think about how to best fix this one.

As a tangent:
-  `exp(est)/(1+exp(est))` is also `plogis()` or more generally `fit$family$link_inv()`
-  In `predict.sdmTMB()`, `se_fit = TRUE` can be really slow unless `re_form = NA` (omit random fields). A faster (and approximate) way if you want random fields included is often setting `nsim` to some value > 0 (e.g., 200) and using `apply(output, 1, sd)`.

**Comment by seananderson** [comment]
A good example by @maxlindmark here: https://github.com/pbs-assess/sdmTMB/issues/160#issuecomment-1380920333

I'm thinking of just removing the type = link/response. It's a mess and would require starting fresh to do it correctly given all the permutations. For now, I'd just not use the argument and always work with the link space output.

**Comment by seananderson** [comment]
I looked into this and realized there was method to the madness but I failed to document or remember it.

If `se_fit = TRUE` I intended to keep the estimate in link space regardless of `type` because the standard errors are calculated in log space. `predict.glm()` on the other hand does let you do `se.fit = TRUE` and `type = "response"`, but it gives you standard errors in the response scale, which we aren't currently calculating.

So, we now issue a warning if `se_fit = TRUE` and `type = "response"`:

``` r
library(sdmTMB)
fit_dg <- sdmTMB(density ~ 1 + s(depth),
  data = pcod_2011,
  mesh = pcod_mesh_2011,
  time = "year",
  spatial = "off",
  spatiotemporal = "off",
  family = delta_gamma()
)
p <- predict(fit_dg, type = 'response', se_fit = TRUE)
#> Warning: predict(..., type = 'response', se_fit = TRUE) detected; returning the
#> prediction 'est' in link space because the standard errors are calculated in
#> link space.
```

<sup>Created on 2023-01-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
At the same time, I also cleared up the related issue raised by @maxlindmark [here](https://github.com/pbs-assess/sdmTMB/issues/160#issuecomment-1380920333). The root of the problem was the `se_fit = TRUE`.

We have a new unit test covering @maxlindmark's example.

**Comment by matteba** [comment]
Great, Thanks again for your amazing work.
