### ISSUE TITLE
Changing barrier mesh through time

### ISSUE THREAD

**Issue by seanhardison1** [pbs-assess/sdmTMB#55]
Hi! I'm a big fan of this package, thanks for your efforts. 

I'd like to model the density of a plant species over time. In this case, the barrier model approach would be a good fit, as the areal extent of the species is known a priori, and the densities of the plant typically decline towards the population boundary, which is irregular over space. However, the tricky part is that the boundary itself is changing through time as the population expands and contracts. 

Is it possible to fit this peculiar type of model in `sdmTMB`? I think I know the answer, but maybe this can serve as a hopeful feature request for future iterations of the package 👍 .

**Comment by kellijohnson-NOAA** [comment]
I will leave it to @seananderson or @ericward-noaa to answer your question regarding the modelling limitations of `sdmTMB`, but I am curious why you wouldn't want to always use the outermost boundary instead of changing the boundary through time because spatial autocorrelation would essentially allow for the outer edges to not be used as the population shrinks towards the center. If the habitat is still available, it doesn't seem like the best idea to limit it from the model because in theory it still has a probability of being inhabited.

**Comment by seanhardison1** [comment]
Hi Kelli, thanks for your response. I think providing some more details would be useful. 

The plants I'm interested in modeling are restored *Zostera marina* eelgrass in the coastal bays of Virginia. There've been large increases in the areal coverage of eelgrass in these bays over the past couple of decades (from nothing to >30 km^2). My concern with using the largest boundary extent is that the boundary is not very similar (in terms of shape or area) to the early years of eelgrass cover. A large portion of the bays is within the habitable zone for eelgrass, so my concern would be that I'd predict its presence where it could have been, and not where it was known to be, which is more aligned with the goals of the project. If I'm misunderstanding your comment then my apologies

All that said, I haven't tried the approach yet, so I'm not sure how much it would matter in the end in terms of estimates of abundance. It might matter very little 🤷

**Comment by ericward-noaa** [comment]
Hey @seanhardison1 - thanks for the thoughts and feedback on the package. Right now, I don't think there's a way to fit a model with a time-varying barrier (or time varying mesh) -- either in sdmTMB, or INLA. 

I think @kellijohnson-NOAA's suggestion is a good alternative. If you fit a model without a shared spatial effect, and only included spatiotemporal variation, I think that would be flexible enough to capture the expansion through time? Or perhaps that, combined with a time-varying covariate that is a good predictor of density ?

A few less elegant ways about this would be to fit each year individually, or try to add in some 0s in places where you know the species isn't in the early years (I think imputing data like this would have to be pretty well justified)

**Comment by seanhardison1** [comment]
hey @kellijohnson-NOAA  and @ericward-noaa, thanks for having a crack at this! I appreciate your insights. It's a fun problem to have. 

I'll give Kelli's suggestion a shot!

**Comment by seananderson** [comment]
Thanks for the feedback, @seanhardison1! A time-varying barrier would require a mesh for each time slice, which I guess would be possible, but would require a bunch of extra book-keeping. My experience is that the barrier mesh doesn't usually make that big of a difference except in fairly contrived situations. People just don't like the *idea* of assuming correlation goes across islands or peninsulas. My guess it makes even less of a difference when we're talking about the outer range boundary. Yes, it will help the random field component decay quickly past the boundary, but hopefully the random fields + covariates are flexible enough to do that for you. Presumably there are observational data that inform you where the boundary is? If so, including those in the model should help it predict near-zero density in those areas. 

If you need more flexibility, or if there are different processes leading to presence-absence and positive density, you could consider a delta/hurdle model with binomial + Gamma or lognormal. You can combine their predictions by multiplying the two in natural space (probability x positive density) and even get uncertainty on that combination with the `sims` argument in `predict.sdmTMB()`.

So, yes, as @kellijohnson-NOAA suggested, I'd start with a mesh around the outer boundary and allow for spatiotemporal random fields so the latent spatial correlation can change through time. You might even consider a custom INLA mesh, making sure it's fine enough around the boundary of interest that it isn't bilinearly interpolating where you don't want that. If you truly know the outer boundary with near-perfect certainty but don't have data collected to model that, you could always just not predict outside the known boundary.

You could go the pseudo-absence generation route (but face the issue of exactly how you do that). I'm assuming you don't have presence-only data.

Since that delta/hurdle-sims approach isn't documented anywhere yet, here's an example:

``` r
library(sdmTMB)
library(ggplot2)

# Bernoulli:
pcod_binom <- pcod_2011
pcod_binom$present <- ifelse(pcod_binom$density > 0, 1L, 0L)
pcod_spde <- make_mesh(pcod_binom, c("X", "Y"), cutoff = 10) # a coarse mesh for example 
plot(pcod_spde)
```

![](https://i.imgur.com/ptbIcV2.png)

``` r
m_bin <- sdmTMB(present ~ 0 + as.factor(year) + depth_scaled + depth_scaled2,
  data = pcod_binom, time = "year", spde = pcod_spde,
  family = binomial(link = "logit"), include_spatial = FALSE)
print(m_bin)
#> Spatiotemporal model fit by ML ['sdmTMB']
#> Formula: present ~ 0 + as.factor(year) + depth_scaled + depth_scaled2
#> Time column: "year"
#> SPDE: pcod_spde
#> Data: pcod_binom
#> Family: binomial(link = 'logit')
#>                     coef.est coef.se
#> as.factor(year)2011     0.35    0.41
#> as.factor(year)2013     1.89    0.44
#> as.factor(year)2015     1.28    0.42
#> as.factor(year)2017     0.41    0.41
#> depth_scaled           -2.08    0.29
#> depth_scaled2          -1.69    0.20
#> 
#> Matern range parameter: 27.41
#> Spatiotemporal SD: 1.89
#> ML criterion at convergence: 483.746
#> 
#> See ?tidy.sdmTMB to extract these values as a data frame.

# Gamma:
pcod_pos <- subset(pcod_2011, density > 0)
m_pos <- make_mesh(pcod_pos, c("X", "Y"), cutoff = 10)
pcod_spde <- make_mesh(pcod_pos, c("X", "Y"), cutoff = 10)
m_pos <- sdmTMB(density ~ 0 + as.factor(year) + depth_scaled + depth_scaled2,
  data = pcod_pos, time = "year", spde = pcod_spde, family = Gamma(link = "log"),
  include_spatial = FALSE) # include_spatial may soon be depreciated
print(m_pos)
#> Spatiotemporal model fit by ML ['sdmTMB']
#> Formula: density ~ 0 + as.factor(year) + depth_scaled + depth_scaled2
#> Time column: "year"
#> SPDE: pcod_spde
#> Data: pcod_pos
#> Family: Gamma(link = 'log')
#>                     coef.est coef.se
#> as.factor(year)2011     4.51    0.18
#> as.factor(year)2013     4.13    0.16
#> as.factor(year)2015     4.13    0.16
#> as.factor(year)2017     3.94    0.18
#> depth_scaled           -0.24    0.14
#> depth_scaled2          -0.28    0.09
#> 
#> Matern range parameter: 8.44
#> Dispersion parameter: 0.95
#> Spatiotemporal SD: 1.67
#> ML criterion at convergence: 2353.554
#> 
#> See ?tidy.sdmTMB to extract these values as a data frame.

# Predictions for each:
qcs_grid_2011 <- subset(qcs_grid, year >= min(pcod_2011$year))
p_bin <- predict(m_bin, newdata = qcs_grid_2011)
p_pos <- predict(m_pos, newdata = qcs_grid_2011)

plot_map <- function(dat, column = "est") {
  ggplot(dat, aes_string("X", "Y", fill = column)) +
    geom_raster() +
    facet_wrap(~year) +
    coord_fixed()
}

plot_map(p_bin, "plogis(est)") +
  scale_fill_viridis_c()
```

![](https://i.imgur.com/i25L8wi.png)

``` r
plot_map(p_pos, "exp(est)") +
  scale_fill_viridis_c(trans = "sqrt")
```

![](https://i.imgur.com/w6egAWc.png)

``` r
# Combined:
p_combined <- dplyr::select(p_bin, X, Y, year)
p_combined$est <- plogis(p_bin$est) * exp(p_pos$est)
plot_map(p_combined, "est") +
  scale_fill_viridis_c(trans = "sqrt")
```

![](https://i.imgur.com/oiusKuz.png)

``` r
# Combined CV:
# (could extract expected mean this way too)
p_bin_sims <- predict(m_bin, newdata = qcs_grid_2011, sims = 500)
p_pos_sims <- predict(m_pos, newdata = qcs_grid_2011, sims = 500)

combined_sims <- plogis(p_bin_sims) * exp(p_pos_sims)
cv <- apply(combined_sims, 1, function(x) sd(x) / mean(x))
cv_df <- data.frame(cv = cv, X = p_combined$X, Y = p_combined$Y, year = p_combined$year)

plot_map(cv_df, "cv") + scale_fill_viridis_c(trans = "log10")
```

![](https://i.imgur.com/KfmaHCi.png)

<sup>Created on 2021-09-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by seanhardison1** [comment]
Hey @seananderson, thanks so much for the detailed response. 

I am definitely one of those people that doesn't like the idea of correlation extending across areas where it shouldn't. I see your point that it wouldn't matter much, but it just bugs me because we have a good idea (not perfect) of where the eelgrass is and isn't in different years, just not its density on a shoots per m basis. 

Another important aspect of the problem is that in situ data from eelgrass meadows are frequently of small sample sizes (<70 per year), so I was thinking that leveraging the known extent of the meadow through a dynamic barrier model could improve predictive accuracy compared to a static one. However, my feeling from this discussion is that the inclusion of spatiotemporal random fields with a static barrier could accomplish something similar?

Also, VIMS (the folks collecting and annotating the imagery) do assign coarse density classes (0-4) to the annotated eelgrass meadow shapes. I bet we could use that information as a second covariate in the model in addition to available in situ data. 

The hurdle model with a larger stationary boundary seems like a good middle ground in all of this to accomplish my objectives, so I'll give it a shot. Thanks again for providing example code.
