### ISSUE TITLE
Uncertainty estimates with predict(,sims=n) for models without random effects

### ISSUE THREAD

**Issue by jnephin** [pbs-assess/sdmTMB#57]
predict(model, sims > 0) does not currently work when there are no random effects (i.e. when sdmTMBcontrol option map_rf = F)

Fails with error message:
Rerunning TMB::sdreport() with `getJointPrecision = TRUE`. 
Error in (function (classes, fdef, mtable) : unable to find an inherited method for function ‘Cholesky’ for signature ‘"NULL"’

**Comment by ericward-noaa** [comment]
I think it's because there's no var-cov matrix for the random effects being estimated. If you just have a model with fixed effects, you can grab the covariance matrix out of the sdreport and simulate from that directly? Here's an example using code from the package's tests: 

set.seed(1)
x <- stats::runif(500, -1, 1)
y <- stats::runif(500, -1, 1)
loc <- data.frame(x = x, y = y)
spde <- make_mesh(loc, c("x", "y"), n_knots = 50, type = "kmeans")
s <- sdmTMB_sim(x = x, y = y,
                betas = 0, time = 1L,
                phi = 0.1, range = 1.4,
                sigma_O = 0.2, sigma_E = 0,
                seed = 1, mesh = spde
)

# random ints match glmmTMB exactly:

m <- sdmTMB(data = s,
            formula = observed ~ 1, spde = spde, control = sdmTMBcontrol(map_rf = TRUE))

predict(m, s) # This works as an example that doesn't use the simulation based approach

predict(m, s, sims=10) # This doesn't work

cov = m$sd_report$cov.fixed # grab covariance matrix that can be used to generate samples
pars = rmvnorm(10000, mu = rep(0, ncol(cov)), Sigma=cov)

**Comment by seananderson** [comment]
Thanks, yeah, and it would be good to check if random effects are present in `rmvnorm_prec()` and if not, just do the above. Or make a different small function than `rmvnorm_prec()`.

**Comment by seananderson** [comment]
This should now be fixed. I also updated Eric's code above to include the mean and what would be needed after to make predictions with it in case anyone stumbles on this in the future.
